import Head from "next/head"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex font-bold text-4xl items-center justify-center min-h-screen">
        Here will be unicorns
      </main>
    </div>
  )
}
