import Head from "next/head"
import Image from "next/image"

import { BiSearch } from "react-icons/bi"
import asset_logo from "@/assets/logo.svg"
import asset_hero from "@/assets/hero.jpg"

export default function Home() {
  return (
    <div>
      <Head>
        <title>topus.digital / Share your knowledge, gain exposure.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen">
        <nav className="p-8 max-w-7xl mx-auto flex gap-12 mt-12 items-start justify-between">
          <div className="flex items-center gap-2">
            <Image height={42} src={asset_logo} alt="" />
            <h3 className="font-black">Topus</h3>
          </div>
          <label className="w-full max-w-sm flex p-3 space-x-2 items-center border-2 overflow-hidden rounded-full border-black">
            <BiSearch className="text-xl" />
            <input
              className="h-full outline-none"
              placeholder="Search for solidity, bakery, science"
              type="text"
            />
          </label>
        </nav>
        <div className="p-8 max-w-7xl mx-auto mb-24 mt-12">
          <h1 className="max-w-3xl text-7xl font-black">
            Share your knowledge, gain exposure.
          </h1>
        </div>
        <section className="relative">
          <div className="inset-0 absolute bg-black/50"></div>
          <Image placeholder="blur" src={asset_hero} alt="" />
        </section>
      </main>
    </div>
  )
}
